# Generated by Django 4.1 on 2022-09-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blogs_Category",
            fields=[
                ("cat_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("url", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, upload_to="category/")),
                ("add_date", models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
