# Generated by Django 4.1 on 2022-09-04 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blogs_Post",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("url", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, upload_to="post/")),
                ("videos", models.FileField(blank=True, upload_to="videos/")),
                ("add_date", models.DateField(auto_now_add=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.blogs_category",
                    ),
                ),
            ],
        ),
    ]
