# Generated by Django 4.1.1 on 2022-09-18 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blogs_category_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogs_category", old_name="add_date", new_name="add_dates",
        ),
        migrations.RenameField(
            model_name="blogs_post", old_name="add_date", new_name="add_dates",
        ),
    ]
