# Generated by Django 4.1.1 on 2022-09-18 09:21

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blogs_Category",
            fields=[
                ("cat_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("description", tinymce.models.HTMLField()),
                ("url", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, upload_to="category/")),
                ("add_date", models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Blogs_Post",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("content", tinymce.models.HTMLField()),
                ("url", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, upload_to="post/")),
                ("videos", models.FileField(blank=True, upload_to="videos/")),
                ("add_date", models.DateField(auto_now_add=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.blogs_category",
                    ),
                ),
            ],
        ),
    ]
