import datetime


AWS_ACCESS_KEY_ID="AKIAW22B6ZMPHXCA5OIX"
AWS_SECRET_ACCESS_KEY="=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"
AWS_FILE_EXPIRE=200
AWS_PRELOAD_METADATA= True
AWS_QUERYSTRING_AUTH=True
AWS_DEFAULT_ACL=None

DEFAULT_FILE_STORAGE = 'saveyourderm.aws.utils.MediaRootS3BototStorage'
STATICFILES_STORAGE='saveyourderm.aws.utils.StaticRootS3BotoStorage'
AWS_STORAGE_BUCKET_NAME='saveyourdermbucket'
AWS_S3_REGION_NAME="ap-south-1"
AWS_S3_SIGNATURE_VERSION="s3v4"

